### ISSUE TITLE
Accessibility - Line 85 - Developer Page

### ISSUE THREAD

**Issue by maabrown** [CommerceDataService/midaas-website#9]
I believe that the ID's used in these lines may not connect with what you want. I think it is supposed to be:

a href="#widgets">Widgets</a

ul class="usa-sidenav-sub_list"

a href="#getting-started">Getting Started</a></li

a href="#widgets-bar-chart">Bar Chart</a></li

a href="#widgets-map">Map</a></li

**Comment by lukad03** [comment]
We linked the parent divs to the first introductory element for each section.
